traintastic/traintastic

- server/CMakeLists.txt
- server/src/os/windows/serialportlistimplwin32.cpp
- server/src/os/windows/trayicon.cpp
- server/src/os/windows/trayicon.hpp
- server/src/utils/endian.hpp
- server/src/utils/setthreadname.cpp
Hello,
This program seems very interesting!
I really like the code style, especially the `InterfaceItem` system which I will study further in the next weeks.
I use MinGW compiler (bundled with Qt package) but in order to build `traintastic-server`, a few fix must be done.
These changes shouldn't affect other systems/compilers because they are all guarded inside `#ifdef`/`#endif`.
Additional changes to the installer would be needed to ship MinGW runtime for MinGW builds.
If you want I can write a separate Pull Request for that.
**NOTE**:
I used **Qt  5.15.2 64-bit** version but the shipped `MinGW (v. 8.1.0)` has a bug in `std::filesystem` header.
To fix the issue I used the newer version `MinGW 11.2.0` (shipped with Qt 6).
When using tools like `windeployqt` pay attention to put the …
> Fix compilation on Windows with MinGW

- server/src/hardware/protocol/traintasticdiy/kernel.cpp
Toggling a disabled input caused crash.
Prevent iterator derefencing when invalid.
Other interfaces, like z21, allow toggling disabled inputs so the behaviour is still correct.
> input: fix TraintasticDIY input simulation

- shared/src/traintastic/board/tilelocation.hpp
It compiles even without it because <cstdint> is included in tileid.hpp But seems to me more correct to have it on both files.
> fix: missing include in tilelocation.hpp

- server/src/core/objectlist.hpp
- server/src/core/tablemodel.cpp
- server/src/core/tablemodel.hpp
When an object is removed from a list, Clients need to clear cached values and reload the model.
This could be more efficient but it will be adressed in a separate pull request.
We can open a new issue specific to Client side sorting and caching
> model: HACK to let client refresh after object is removed

- server/src/log/consolelogger.cpp
- server/src/log/filelogger.cpp
- server/src/log/logger.hpp
- Conform ConsoleLogger and FileLogger to use same format in 'std::put_time()'
- Workaround missing specifier support in MinGW 12.2.0 by using old pre-C+ +11 specifiers.
See #35
> Logger workaround for MinGW broken std::put_time()

- BUILDING.md
Added instructions specific to MinGW.
Linked GDB online documentation.
I must say I don't like the document layout because instructions are duplicated almost same for Client and Server.
But that's a minor thing.
I added information about debugging which are entirely missing for other setups.
Maybe something should be added for them too, and something is common to many compilers
> Add MinGW section to BUILDING.md

- client/src/board/tilepainter.cpp
- server/src/board/map/signalpath.cpp
- server/src/board/tile/rail/turnout/turnoutdoublesliprailtile.cpp
- server/src/board/tile/rail/turnout/turnoutsinglesliprailtile.cpp
- shared/src/traintastic/enum/turnoutposition.hpp
- This adds Left/Right to double switch
- And adds new DoubleSlipStraightA / DoubleSlipStraightB to TurnoutPosition enum
- Implemented new state drawing in TilePainter
- Updated logic in SignalPath::findBlocks()
Hi, this PR implements features of #15.
It's a quick test so might break code style but the logic seems fine.
Maybe the names of new states should be changed...
Also it would be good to initialize `outputMap.setValueInternal()` with `positionValues` array to avoid duplicating the list.
Closes #15
> Add 4 new positions to Double Slip Switch turnout

- client/src/widget/objectlist/objectlistwidget.cpp
- client/src/widget/objectlist/objectlistwidget.hpp
- server/src/train/train.cpp
This fixes move Up/Down not disabled when train is moving.
In the second commit I've fixed a clang warning not strictly related to this issue, maybe there are more of them in other places.
> Fix train vehicle list

- server/src/hardware/protocol/z21/clientkernel.cpp
- server/src/hardware/protocol/z21/clientkernel.hpp
- server/src/hardware/protocol/z21/iohandler/simulationiohandler.cpp
- server/src/hardware/protocol/z21/kernel.hpp
- server/src/hardware/protocol/z21/messages.cpp
- server/src/hardware/protocol/z21/messages.hpp
- server/src/hardware/protocol/z21/serverkernel.cpp
- server/src/hardware/protocol/z21/serverkernel.hpp
- server/src/hardware/protocol/z21/utils.hpp
- shared/src/traintastic/enum/logmessage.hpp
- shared/translations/en-us.txt
Request BC flags as keep alive timer until we get a valid reply
Maybe we should allow a Z21 not supporting BC flags? Currently if Z21 replies "None", traintastic keeps asking again.
This can be because:
- the "set" part was skipped and we received only original BC flags -> ask again (current behaviour)
- The Z21 does not support BC flags so "None" is actually the correct status -> switch to normal keep alive message
I think we should consider also the second case
> server: Z21 fix bradcast flags and other small fixes

- utils/check-sources.py
Fix python script on Windows by opening files in UTF-8
> Utils: fix python scripts on Windows

- server/src/hardware/protocol/xpressnet/messages.cpp
- server/src/hardware/protocol/xpressnet/messages.hpp
- server/src/hardware/protocol/z21/clientkernel.cpp
- server/src/hardware/protocol/z21/clientkernel.hpp
- server/src/hardware/protocol/z21/iohandler/simulationiohandler.cpp
- server/src/hardware/protocol/z21/messages.cpp
- server/src/hardware/protocol/z21/messages.hpp
- server/src/hardware/protocol/z21/serverkernel.cpp
- server/src/hardware/protocol/z21/utils.hpp
Hi! These changes are extracted from other PRs, mainly #59 and #73, #56 and do not change behavior except bug fixing.
- d9ace24d88c32cd768a6e93ee4e17280558803b2 First commit is a short term solution to #53 but can also be kept afterwards as it's better to capture as less as possible.
- 0e463ff8fe97889b0921bda4b519e8f28058d2ce Can be explained a bit better, test if you run in race condition by connecting station in a different world state than Traintastic and see who imposes it's state on the other.
- b48e8f75069e79d5c3e021e3d52c795c89f028a4 Double check format is now correct
- 488663331dbbc002491a8d9c5a72799659f3f85e There are still other hardcoded values in `simulationiohandler.cpp` and `serverkernel.cpp` which can be labelled but didn't know what names to give them.
> New Z21 fixes

- server/src/hardware/decoder/decoderchangeflags.hpp
- server/src/hardware/protocol/z21/clientkernel.cpp
- server/src/hardware/protocol/z21/clientkernel.hpp
- server/src/hardware/protocol/z21/config.hpp
- server/src/hardware/protocol/z21/messages.cpp
- server/src/hardware/protocol/z21/messages.hpp
Replaces #59
This PR handles receiving loco state from Z21 and update relevant Decoders.
Needs #81 first
- Added support for receiving F29 - F31 (When Z21 firmware version is >= 1.42)
- Fix infinite loop explained in issue #57 (only mitigated)
> Z21 handle loco info 2

- client/src/network/abstractproperty.hpp
Fixes a compile error when disabling deprecated functions
> client: port QVariant::Type to QMetaType::Type

- server/src/board/tile/rail/signal/signal2aspectrailtile.cpp
- server/src/board/tile/rail/signal/signal3aspectrailtile.cpp
- server/src/board/tile/rail/turnout/turnout3wayrailtile.cpp
- server/src/board/tile/rail/turnout/turnoutdoublesliprailtile.cpp
- server/src/board/tile/rail/turnout/turnoutleftrailtile.cpp
- server/src/board/tile/rail/turnout/turnoutrightrailtile.cpp
- server/src/board/tile/rail/turnout/turnoutsinglesliprailtile.cpp
- server/src/board/tile/rail/turnout/turnoutwyerailtile.cpp
- server/src/core/attributes.hpp
- server/src/core/interfaceitem.hpp
- server/src/core/spanattribute.hpp
- Invert template order in Attributes::addValues()
- Unfortunately template parameter is not deduced automatically because of `const` in span template
- More could be done for OutputMap
> More tcb::span usage for Attributes::addValues()

- server/src/hardware/protocol/z21/messages.hpp
Most significant address byte is first (DB0)
This fixes parsing of `LAN_X_TURNOUT_INFO` replies from Z21 which would otherwise activate wrong output once #113 gets merged.
Also `LAN_X_EXT_ACCESSORY_INFO` and `LAN_X_GET_EXT_ACCESSORY_INFO` are missing. I'll draft an implementation.
> server: Z21 fix LanXTurnoutInfo member order

- server/src/hardware/protocol/z21/clientkernel.cpp
- server/src/hardware/protocol/z21/iohandler/simulationiohandler.cpp
- server/src/hardware/protocol/z21/messages.cpp
- server/src/hardware/protocol/z21/messages.hpp
- Support querying and obtaining DCCExt accessory status
Added also simulation code and logging strings.
> server: Z21 add LanXExtAccessoryInfo message

- shared/traintastic.cmake
removed system level requirement for lsb_release which isn't always installed on all Linux distros.
Cmake has an inbuilt function for getting host system-level environment variables.
https://cmake.org/cmake/help/latest/command/cmake_host_system_information.html#query-host-system-specific-information
> removed system requirement for lsb_release

- server/src/hardware/interface/z21interface.cpp
- server/src/hardware/protocol/z21/clientkernel.cpp
- server/src/hardware/protocol/z21/clientkernel.hpp
- server/src/hardware/protocol/z21/messages.hpp
This fixes power state changes being ignored from both end at times or annoying repeated changes in loop.
By the way, I've finally succeeded in making myself a small Z21 with an ESP32 and using Philipp Gahtow libraries ([available here](https://www.pgahtow.de/w/Z21_mobile/en)) with some patches on top to make it work better and as an XpressNet slave.
I cannot test with a real Z21 but you maybe could test with Digikeijs DR5000.
Should fix #85
> Fix z21 power state

- server/src/hardware/protocol/loconet/iohandler/lbserveriohandler.cpp
\n\r handles in both directions as well \r\n as well as just \n or \r
Got stuck in a loop after reading the new line character it didn't count it in the loop, so ignored it and kept looping.
> Fixed new line character skipping

- server/src/hardware/protocol/z21/clientkernel.cpp
This reverts commit 5a291f0c914c904c98dcd3d1f0434f05bf31f39e.
This workaround is not needed anymore after commit 161a0e9521bc3ef30c799234d3f82d84b971afdd
> Revert "server: Z21 ClientKernel fix crash on disconnect"

- server/src/hardware/protocol/z21/clientkernel.cpp
- server/src/hardware/protocol/z21/clientkernel.hpp
- server/src/hardware/protocol/z21/iohandler/simulationiohandler.cpp
- server/src/hardware/protocol/z21/iohandler/simulationiohandler.hpp
- server/src/hardware/protocol/z21/messages.cpp
- server/src/hardware/protocol/z21/messages.hpp
- server/src/hardware/protocol/z21/serverkernel.cpp
Pending request queue allows to retry sending messages after a timeout if expected reply is not received.
This also allows to detect a message is a reply to our own changes and react to it differently
See #60 for earlier discussion.
NOTE: needs #82 applied first
Both this and #82 `LocoCache` try to resolve the "async loop" issue (See #57).
This 2 solutions are orthogonal and can live together.
> Z21 pending request queue

- client/src/dialog/connectdialog.cpp
Fixes compilation with QT deprecated > 6.9
> ConnectDialog: use QCheckBox::checkStateChanged() from Qt 6.7

- simulator/src/simulator.cpp
Adds to PR #185 
Fixes next segment side calculation and adds turnout support starting from "curve".
Attached sample oval station with 4 turnouts.
[oval_station_double.json](https://github.com/user-attachments/files/19740553/oval_station_double.json)
Still we cannot specify to which side we want to attach to previous segment, but only our side can be set explicitly.
So when putting a turnout, next segment will always be attached to its straight end.
Only after that, you can attach something to turnout's curve end.
> Simulator Turnouts
